#!/bin/bash

## declare an array variable
# declare -a arr=("element1" "element2" "element3")


# You can access them using echo "${arr[0]}", "${arr[1]}" also


# classes, let’s do from 5 to 2000, make 20 cases? time Slots, from 5 to 100, make 10 cases. So that’s 200 cases — do you think you can write a script to do it? Doing it by hand would be painful


# a=2334                   # Integer.
# let "a += 1"
# echo "a = $a "           # a = 2335
# echo                     # Integer, still.
minS=5
maxS=2000

CLASSES=()

# for ((i = 0; i<5; i++)); do
#     # echo "Element $i"
#     CLASSES+=(5)
# done


for ((i = 100; i<=maxS; i+=(maxS/20))); do
    # echo "Element $i"
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
done


# echo "${CLASSES[@]}"
# echo "${#CLASSES[@]}"


minT=5
maxT=100

TIMES=()
for ((i = minT; i<=maxT; i+=(maxT/5))); do
    # echo "Element $i"
    # for ((i = 0; i<minT; i++)); do
    TIMES+=($i)
    # done 
done



maxR=500
ROOMS=()
for ((i = 50; i<=maxR; i+=(maxR/10))); do
    # echo "Element $i"
    # for ((i = 0; i<minT; i++)); do
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    # done 
done


echo "${ROOMS[@]}"
echo "${#ROOMS[@]}"



echo -n "" > listoftests.txt
# now loop through the above array
echo -e "numRooms \t numClasses \t numSlots \t numStudent" >> listoftests.txt 
y=0
x=0
for ((i = 0; i<${#CLASSES[@]}; i++)); do
    echo -e "${ROOMS[$i]} \t ${CLASSES[$i]} \t ${TIMES[$x]} \t 1000" >> listoftests.txt
    echo -n "" > basic/constraints.txt
    echo -n "" > basic/pref.txt
    perl basic/make_random_input.pl 50 ${CLASSES[$i]} ${TIMES[$x]} 1000 basic/constraints.txt basic/pref.txt
    python ClassScheduling.py

    ((x++))
    ((y++))
    if [[ $(( $x % 5 )) == 0 ]]; then
        x=0 
    fi

    if [[ $(( $y % 10 )) == 0 ]]; then
        y=0 
    fi

   # or do whatever with individual element of the array
done

# for ((i = 0; i<=2; i++)); do
#     echo -n "" > basic/constraints.txt
#     echo -n "" > basic/pref.txt
#     perl basic/make_random_input.pl 50 i i 1000 basic/constraints.txt basic/pref.txt
#     python ClassScheduling.py
# done

