#!/bin/bash

minS=5
maxS=2000

CLASSES=()

for ((i = 100; i<=maxS; i+=(maxS/20))); do
    # echo "Element $i"
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
    CLASSES+=($i)
done


# echo "${CLASSES[@]}"
# echo "${#CLASSES[@]}"


minT=5
maxT=100

TIMES=()
for ((i = minT; i<=maxT; i+=(maxT/5))); do
    # echo "Element $i"
    # for ((i = 0; i<minT; i++)); do
    TIMES+=($i)
    # done 
done



maxR=500
ROOMS=()
for ((i = 50; i<=maxR; i+=(maxR/10))); do
    # echo "Element $i"
    # for ((i = 0; i<minT; i++)); do
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    ROOMS+=($i)
    # done 
done


echo "${ROOMS[@]}"
echo "${#ROOMS[@]}"



echo -n "" > listoftests.txt
# now loop through the above array
echo -e "numRooms \t numClasses \t numSlots \t numStudent \t seconds \t opt" >> listoftests.txt 
y=0
x=0
for ((i = 0; i<${#CLASSES[@]}; i++)); do
    echo -n "" > basic/constraints.txt
    echo -n "" > basic/pref.txt
    perl basic/make_random_input.pl 50 ${CLASSES[$i]} ${TIMES[$x]} 1000 basic/constraints.txt basic/pref.txt
    python ClassScheduling.py
   
    VARIABLE=`python ClassScheduling.py`
    echo -e "${ROOMS[$i]} \t ${CLASSES[$i]} \t ${TIMES[$x]} \t 1000 \t ${VARIABLE} \n " >> listoftests.txt
    # echo ${VARIABLE}
    ((x++))
    ((y++))
    if [[ $(( $x % 5 )) == 0 ]]; then
        x=0 
    fi

    if [[ $(( $y % 10 )) == 0 ]]; then
        y=0 
    fi

done

